SELECT
	TABLE_NAME AS 'Table without class'
FROM INFORMATION_SCHEMA.TABLES
WHERE
	TABLE_TYPE = 'BASE TABLE'
	AND TABLE_NAME NOT IN (SELECT ClassTableName FROM CMS_Class WHERE ClassTableName IS NOT NULL)
	AND TABLE_NAME NOT IN ('CD_Migration', 'CI_Migration')
ORDER BY
	TABLE_NAME